### ISSUE TITLE
Perms issue when deploying the provided template to OpenShift

### ISSUE THREAD

**Issue by philipgough** [wtrocki/rhmap_nginx_proxy#2]
@wtrocki 

As per title, when attempting to create the app inside a new project OpenShift through the following error:

```
Error creating: pods "nginx-proxy-4-" is forbidden: unable to validate against any security context constraint: [securityContext.runAsUser: Invalid value: 998: UID on container nginx-proxy does not match required range. Found 998, required min: 1000200000 max: 1000209999]
```
I tried to update the policy by setting the default ServiceAccount which is referenced in the template to the privileged but the same error exists

**Comment by wtrocki** [comment]
To run this on production like cluster different securitycontext constraint should be attached to the project. To resolve problem I would use UID bigger than 1000 and set user in the template directly.

**Comment by wtrocki** [comment]
Resolved :)
